const RestaurantList = [
    {
        id: 0,
        category: 'Cafe',
        name: "Gloria-Jeans",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Gloria-Jeans.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/biscuits1.jpg'),
                itemName: 'Biscuits 852',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14, 
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/sandwich2.jpg'),
                itemName: 'Sandwich 982',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/pastries4.jpg'),
                itemName: 'Pastries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/pastries1.jpg'),
                itemName: 'Pastries Cho',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 1,
        category: 'Cafe',
        name: "Butlers-Chocolate-Cafe",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Butlers-Chocolate-Cafe.png'),
        rating: 4.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/biscuits2.jpg'),
                itemName: 'Biscuits 963',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 6,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/cake6.jpg'),
                itemName: 'Cake 254',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/sandwich1.jpg'),
                itemName: 'Sandwich 980',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 7,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/tea2.jpg'),
                itemName: 'Black Tea',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 2,
        category: 'Cafe',
        name: "Filli-Cafe",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4'],
        picture: require('../assets/img/restaurantIcon/Filli-Cafe.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/sandwich5.jpg'),
                itemName: 'Bake Sandwich ',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/pastries2.jpg'),
                itemName: 'Pastries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/coffee1.jpg'),
                itemName: 'Coffee',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/juice3.jpg'),
                itemName: 'Orange Juice',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
        ]
    },
    {
        id: 3,
        category: 'Cafe',
        name: "Xanders",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Xanders.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/coffee2.jpg'),
                itemName: 'Coffee',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/tea4.jpg'),
                itemName: 'Green Tea',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/juice3.jpg'),
                itemName: 'Juice',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/cake5.jpg'),
                itemName: 'Cup Cake',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
        ]
    },
    {
        id: 4,
        category: 'Cafe',
        name: "Subway",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5'],
        picture: require('../assets/img/restaurantIcon/Subway.png'),
        rating: 2.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/juice4.jpg'),
                itemName: 'Juice',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 12,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/sandwich3.jpg'),
                itemName: 'Sandwich',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/biscuits3.jpg'),
                itemName: 'Biscuits',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/tea3.jpg'),
                itemName: 'Tea',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 10,
            },
        ]
    },
    {
        id: 5,
        category: 'Cafe',
        name: "Del-Frio",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Del-Frio.png'),
        rating: 5.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/juice2.jpg'),
                itemName: 'Juice',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/tea1.jpg'),
                itemName: 'Tea',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/pastries1.jpg'),
                itemName: 'Pastries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 15,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/pastries3.jpg'),
                itemName: 'Pastries 852',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 7,
            },
        ]
    },
    {
        id: 6,
        category: 'Cafe',
        name: "Dunkin-Donuts",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5', 'Branch6'],
        picture: require('../assets/img/restaurantIcon/Dunkin-Donuts.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/cafe/pastries4.jpg'),
                itemName: 'Pastries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/cafe/sandwich5.jpg'),
                itemName: 'Sandwich',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/cafe/tea1.jpg'),
                itemName: 'Tea',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/cafe/juice4.jpg'),
                itemName: 'Juice',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 6,
            },
        ]
    },
    {
        id: 7,
        category: 'Pizza',
        name: "Pizza-Max",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Pizza-Max.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Pizza/bakePizza1.jpg'),
                itemName: 'Bake Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Pizza/chickenTikkaPizza1.jpg'),
                itemName: 'Chicken Tikka Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Pizza/chickenTikkaPizza2.jpg'),
                itemName: 'Chicken Tikka Pizza 630',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Pizza/creamyPizza1.jpg'),
                itemName: 'Creamy Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 6,
            },
        ]
    },
    {
        id: 8,
        category: 'Pizza',
        name: "Pizza-Point",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Pizza-Point.png'),
        rating: 1.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Pizza/vegetablePizza2.jpg'),
                itemName: 'Vegetable Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Pizza/vegetablePizza1.jpg'),
                itemName: 'Vegetable Pizza 970',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Pizza/tomatoPizza1.jpg'),
                itemName: 'Tomato Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Pizza/pepperoniPizza1.jpg'),
                itemName: 'Pepperoni Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 10,
            },
        ]
    },
    {
        id: 9,
        category: 'Pizza',
        name: "California-Pizza",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4'],
        picture: require('../assets/img/restaurantIcon/California-Pizza.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Pizza/penPizza1.jpg'),
                itemName: 'Pen Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Pizza/eggPizza1.jpg'),
                itemName: 'Egg Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Pizza/creamyPizza1.jpg'),
                itemName: 'Creamy Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Pizza/bakePizza1.jpg'),
                itemName: 'Bake Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
        ]
    },
    {
        id: 10,
        category: 'Pizza',
        name: "Dominos-Pizza",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Dominos-Pizza.png'),
        rating: 2.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Pizza/chickenTikkaPizza3.jpg'),
                itemName: 'Chicken Tikka Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Pizza/chickenTikkaPizza2.jpg'),
                itemName: 'Chicken Tikka Pizza 004',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 14,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Pizza/chickenTikkaPizza1.jpg'),
                itemName: 'Chicken Tikka Pizza 740',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Pizza/eggPizza1.jpg'),
                itemName: 'Egg Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 7,
            },
        ]
    },
    {
        id: 11,
        category: 'Pizza',
        name: "The-New-York-Pizza",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/The-New-York-Pizza.png'),
        rating: 1.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Pizza/tomatoPizza1.jpg'),
                itemName: 'Tomato Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 12,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Pizza/vegetablePizza1.jpg'),
                itemName: 'Vegetable Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Pizza/eggPizza1.jpg'),
                itemName: 'Egg Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Pizza/vegetablePizza2.jpg'),
                itemName: 'Vegetable Pizza',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 6,
            },
        ]
    },
    {
        id: 12,
        category: 'FastFood',
        name: "Karachi-Broast",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Karachi-Broast.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/FastFood/chickenWings1.jpg'),
                itemName: 'Chicken Wings',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 12,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/FastFood/FastFood3.jpg'),
                itemName: 'Fast Food Deal 985',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/FastFood/FastFood7.jpg'),
                itemName: 'Fast Food Deal 914',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/FastFood/FastFood10.jpg'),
                itemName: 'Fast Food Deal 004',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 6,
            },
        ]
    },
    {
        id: 13,
        category: 'FastFood',
        name: "Kbc-Restaurant",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Kbc-Restaurant.png'),
        rating: 1.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/FastFood/FastFood4.jpg'),
                itemName: 'Fast Food Deal 350',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/FastFood/chickenWings3.jpg'),
                itemName: 'Chicken Wings 360',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/FastFood/FastFood6.jpg'),
                itemName: 'Fast Food Deal 720',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/FastFood/chickenWings2.jpg'),
                itemName: 'Chicken Wings 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 14,
        category: 'FastFood',
        name: "Kaybees-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Kaybees-Restaurant.png'),
        rating: 2.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/FastFood/FastFood3.jpg'),
                itemName: 'Fast Food Deal 008',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/FastFood/FastFood7.jpg'),
                itemName: 'Fast Food Deal 990',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/FastFood/fries1.jpg'),
                itemName: 'Fries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/FastFood/chickenWings2.jpg'),
                itemName: 'Fries 980',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 7,
            },
        ]
    },
    {
        id: 15,
        category: 'FastFood',
        name: "Foods-Inn",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Foods-Inn.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/FastFood/FastFood9.jpg'),
                itemName: 'Fast Food Deal 370',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/FastFood/chickenWings1.jpg'),
                itemName: 'Chicken Wings',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/FastFood/fries3.jpg'),
                itemName: 'Fries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/FastFood/FastFood4.jpg'),
                itemName: 'Fast Food Deal 660',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 16,
        category: 'FastFood',
        name: "Khan-Broast",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Khan-Broast.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/FastFood/FastFood6.jpg'),
                itemName: 'Fast Food Deal 870',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/FastFood/chickenWings2.jpg'),
                itemName: 'Chicken Wings',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/FastFood/fries1.jpg'),
                itemName: 'Fries',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 6,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/FastFood/FastFood7.jpg'),
                itemName: 'Fast Food Deal 999',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 11,
            },
        ]
    },
    {
        id: 17,
        category: 'Buffet',
        name: "Lal-Qila-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Lal-Qila-Restaurant.png'),
        rating: 2.5,
        menuList: [],
    },
    {
        id: 18,
        category: 'Buffet',
        name: "Rangoli-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Rangoli-Restaurant.png'),
        rating: 3.5,
        menuList: [],
    },
    {
        id: 19,
        category: 'Buffet',
        name: "Clock-Tower-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Clock-Tower-Restaurant.png'),
        rating: 4.5,
        menuList: [],
    },
    {
        id: 20,
        category: 'Buffet',
        name: "Chopal-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Chopal-Restaurant.png'),
        rating: 3.5,
        menuList: [],
    },
    {
        id: 21,
        category: 'BarBq',
        name: "Red-Apple",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Red-Apple.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/BarBq/BarBq1.jpg'),
                itemName: 'BarBq 258',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/BarBq/BarBq2.jpg'),
                itemName: 'BarBq 604',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/BarBq/BarBq3.jpg'),
                itemName: 'BarBq 709',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/BarBq/BarBq4.jpg'),
                itemName: 'BarBq 654',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 12,
            },
        ]
    },
    {
        id: 22,
        category: 'BarBq',
        name: "Hot-n-Spicy",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5', 'Branch6'],
        picture: require('../assets/img/restaurantIcon/Hot-n-Spicy.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/BarBq/BarBq5.jpg'),
                itemName: 'BarBq 117',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/BarBq/BarBq6.jpg'),
                itemName: 'BarBq 336',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/BarBq/BarBq7.jpg'),
                itemName: 'BarBq 870',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 23,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/BarBq/BarBq8.jpg'),
                itemName: 'BarBq 008',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
        ]
    },
    {
        id: 23,
        category: 'BarBq',
        name: "Hot-n-Roll",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Hot-n-Roll.png'),
        rating: 2.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/BarBq/BarBq9.jpg'),
                itemName: 'BarBq 650',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/BarBq/BarBq10.jpg'),
                itemName: 'BarBq 880',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/BarBq/BarBq1.jpg'),
                itemName: 'BarBq 330',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/BarBq/BarBq2.jpg'),
                itemName: 'BarBq 770',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 19,
            },
        ]
    },
    {
        id: 24,
        category: 'BarBq',
        name: "Zameer-Ansari",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Zameer-Ansari.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/BarBq/BarBq3.jpg'),
                itemName: 'BarBq 340',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/BarBq/BarBq4.jpg'),
                itemName: 'BarBq 357',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/BarBq/BarBq5.jpg'),
                itemName: 'BarBq 970',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/BarBq/BarBq6.jpg'),
                itemName: 'BarBq 360',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 21,
            },
        ]
    },
    {
        id: 25,
        category: 'BarBq',
        name: "Barbq-Tonight",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Barbq-Tonight.png'),
        rating: 3.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/BarBq/BarBq7.jpg'),
                itemName: 'BarBq 258',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 23,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/BarBq/BarBq8.jpg'),
                itemName: 'BarBq 440',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/BarBq/BarBq9.jpg'),
                itemName: 'BarBq 339',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/BarBq/BarBq10.jpg'),
                itemName: 'BarBq 660',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
        ]
    },
    {
        id: 26,
        category: 'Chinese',
        name: "Meikong-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Meikong-Restaurant.png'),
        rating: 4.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Chinese/Chinese6.jpg'),
                itemName: 'Chinese 660',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Chinese/chineseChili.jpg'),
                itemName: 'Chinese Chili',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Chinese/ChineseNoodles.jpg'),
                itemName: 'Chinese Noodles',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 17,
            },
        ]
    },
    {
        id: 27,
        category: 'Chinese',
        name: "China-Grill-Restaurant",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/China-Grill-Restaurant.png'),
        rating: 3.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Chinese/chineseSoup1.jpg'),
                itemName: 'Chinese Soup',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 10,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Chinese/Chinese6.jpg'),
                itemName: 'Chinese',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 28,
        category: 'Chinese',
        name: "Ginsoy-Restaurant",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5'],
        picture: require('../assets/img/restaurantIcon/Ginsoy-Restaurant.png'),
        rating: 4.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Chinese/chineseSoup2.jpg'),
                itemName: 'Chinese Soup',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 10,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Chinese/chineseChili.jpg'),
                itemName: 'Chinese Chili',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Chinese/Chinese6.jpg'),
                itemName: 'Chinese',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 29,
        category: 'Chinese',
        name: "Bambou-Restaurant",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Bambou-Restaurant.png'),
        rating: 3.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Chinese/chineseSoup1.jpg'),
                itemName: 'Chinese Soup',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 12,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Chinese/chineseChili.jpg'),
                itemName: 'Chinese Chili',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 10,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Chinese/Chinese6.jpg'),
                itemName: 'Chinese',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 11,
            },
        ]
    },
    {
        id: 30,
        category: 'Chinese',
        name: "Chowmein-Restaurant",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Chowmein-Restaurant.png'),
        rating: 2.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Chinese/chineseSoup2.jpg'),
                itemName: 'Chinese Soup',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Chinese/chickenChowmein.jpg'),
                itemName: 'Chicken Chowmein',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 15,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Chinese/ChineseNoodles.jpg'),
                itemName: 'Chinese Noodles',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Chinese/chineseSoup1.jpg'),
                itemName: 'Chinese Soup',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
        ]
    },
    {
        id: 31,
        category: 'DesiFood',
        name: "Rehman-Biryani",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Rehman-Biryani.png'),
        rating: 4.5,
        menuList: [],
    },
    {
        id: 32,
        category: 'DesiFood',
        name: "Allah-Wala-Biryani",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Allah-Wala-Biryani.png'),
        rating: 3.5,
        menuList: [],
    },
    {
        id: 33,
        category: 'DesiFood',
        name: "Qadri-Nalli-Biryani",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Qadri-Nalli-Biryani.png'),
        rating: 4.9,
        menuList: [],
    },
    {
        id: 34,
        category: 'DesiFood',
        name: "Ghousia-Nalli-Biryani",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Ghousia-Nalli-Biryani.png'),
        rating: 3.5,
        menuList: [],
    },
    {
        id: 35,
        category: 'DesiFood',
        name: "Naseeb-Biryani",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5'],
        picture: require('../assets/img/restaurantIcon/Naseeb-Biryani.png'),
        rating: 4.5,
        menuList: [],
    },
    {
        id: 36,
        category: 'DesiFood',
        name: "Zahid-Nihari",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Zahid-Nihari.png'),
        rating: 4.2,
        menuList: [],
    },
    {
        id: 37,
        category: 'DesiFood',
        name: "Javed-Nihari",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Javed-Nihari.png'),
        rating: 4.3,
        menuList: [],
    },
    {
        id: 38,
        category: 'Burgers',
        name: "Burger-Lab",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5', 'Branch6'],
        picture: require('../assets/img/restaurantIcon/Burger-Lab.png'),
        rating: 3.3,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger1.jpg'),
                itemName: 'Burger 990',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger2.jpg'),
                itemName: 'Burger 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger3.jpg'),
                itemName: 'Burger 741',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger4.jpg'),
                itemName: 'Burger 310',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 39,
        category: 'Burgers',
        name: "Burger-King",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4'],
        picture: require('../assets/img/restaurantIcon/Burger-King.png'),
        rating: 4.3,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger5.jpg'),
                itemName: 'Burger 740',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 13,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger6.jpg'),
                itemName: 'Burger 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger7.jpg'),
                itemName: 'Burger 369',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger8.jpg'),
                itemName: 'Burger 440',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
        ]
    },
    {
        id: 40,
        category: 'Burgers',
        name: "Burger-o-Clock",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Burger-o-Clock.png'),
        rating: 4.9,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger9.jpg'),
                itemName: 'Burger 330',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger10.jpg'),
                itemName: 'Burger 880',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger1.jpg'),
                itemName: 'Burger 114',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger2.jpg'),
                itemName: 'Burger 707',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 6,
            },
        ]
    },
    {
        id: 41,
        category: 'Burgers',
        name: "The-Sauce-Burger-Cafe",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/The-Sauce-Burger-Cafe.png'),
        rating: 3.7,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger4.jpg'),
                itemName: 'Burger 698',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 3,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger6.jpg'),
                itemName: 'Burger 570',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger8.jpg'),
                itemName: 'Burger 222',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger3.jpg'),
                itemName: 'Burger 367',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 42,
        category: 'Burgers',
        name: "KFC",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4', 'Branch5', 'Branch6', 'Branch7'],
        picture: require('../assets/img/restaurantIcon/KFC.png'),
        rating: 4.7,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger1.jpg'),
                itemName: 'Burger 257',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 3,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger3.jpg'),
                itemName: 'Burger 470',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger4.jpg'),
                itemName: 'Burger 080',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger9.jpg'),
                itemName: 'Burger 097',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 43,
        category: 'Burgers',
        name: "The-Burger-Shack",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/The-Burger-Shack.png'),
        rating: 2.7,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger2.jpg'),
                itemName: 'Burger 240',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 3,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger4.jpg'),
                itemName: 'Burger 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger6.jpg'),
                itemName: 'Burger 009',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger8.jpg'),
                itemName: 'Burger 000',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 44,
        category: 'Burgers',
        name: "Mcdonalds",
        branches: ['Branch1', 'Branch2', 'Branch3', 'Branch4'],
        picture: require('../assets/img/restaurantIcon/Mcdonalds.png'),
        rating: 4.7,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger1.jpg'),
                itemName: 'Burger 700',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 3,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger3.jpg'),
                itemName: 'Burger 390',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger9.jpg'),
                itemName: 'Burger 025',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger2.jpg'),
                itemName: 'Burger 980',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 9,
            },
        ]
    },
    {
        id: 45,
        category: 'Burgers',
        name: "Optp",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Optp.png'),
        rating: 4.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Burgers/Burger10.jpg'),
                itemName: 'Burger 001',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 5,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Burgers/Burger2.jpg'),
                itemName: 'Burger 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 7,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Burgers/Burger3.jpg'),
                itemName: 'Burger 009',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 4,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Burgers/Burger4.jpg'),
                itemName: 'Burger 330',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 14,
            },
        ]
    },
    {
        id: 46,
        category: 'Steakhouses',
        name: "Meat-The-Cheese",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Meat-The-Cheese.png'),
        rating: 3.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks1.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks1.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/muttonSteaks2.jpg'),
                itemName: 'Mutton Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 19,
            },
        ]
    },
    {
        id: 47,
        category: 'Steakhouses',
        name: "Arizona-Grill",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Arizona-Grill.png'),
        rating: 2.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks2.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks3.jpg'),
                itemName: 'Beef Steaks 007',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks2.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
        ]
    },
    {
        id: 48,
        category: 'Steakhouses',
        name: "Gunsmoke",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Gunsmoke.png'),
        rating: 4.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/muttonSteaks1.jpg'),
                itemName: 'Mutton Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks3.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks1.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks3.jpg'),
                itemName: 'Beef Steaks 990',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
        ]
    },
    {
        id: 49,
        category: 'Steakhouses',
        name: "Grill-House",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Grill-House.png'),
        rating: 2.8,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks1.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 15,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks1.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 16,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/muttonSteaks2.jpg'),
                itemName: 'Mutton Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 21,
            },
        ]
    },
    {
        id: 50,
        category: 'Steakhouses',
        name: "Jardin",
        branches: ['Branch1'],
        picture: require('../assets/img/restaurantIcon/Jardin.png'),
        rating: 4.3,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks2.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks2.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 13,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/muttonSteaks1.jpg'),
                itemName: 'Mutton Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 8,
            },
        ]
    },
    {
        id: 51,
        category: 'Steakhouses',
        name: "Sizzlerz",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Sizzlerz.png'),
        rating: 3.3,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Steakhouses/beefSteaks1.jpg'),
                itemName: 'Beef Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 11,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 19,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Steakhouses/fishSteaks2.jpg'),
                itemName: 'Fish Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 13,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Steakhouses/chickenSteaks1.jpg'),
                itemName: 'Chicken Steaks',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 17,
            },
        ]
    },
    {
        id: 52,
        category: 'Icecream',
        name: "Creamello",
        branches: ['Branch1', 'Branch2', 'Branch3'],
        picture: require('../assets/img/restaurantIcon/Creamello.png'),
        rating: 4.3,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Icecream/Icecream1.jpg'),
                itemName: 'Icecream',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 14,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone3.jpg'),
                itemName: 'Icecream Cone',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 11,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Icecream/IcecreamWaffle1.jpg'),
                itemName: 'Icecream Waffle',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 20,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone4.jpg'),
                itemName: 'Icecream Cone Pink',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 8,
            },
        ]
    },
    {
        id: 53,
        category: 'Icecream',
        name: "Baskin-Robbins",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/Baskin-Robbins.png'),
        rating: 4.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Icecream/Icecream2.jpg'),
                itemName: 'Icecream',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 12,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Icecream/Icecream8.jpg'),
                itemName: 'Icecream Cho',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 18,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone1.jpg'),
                itemName: 'Icecream Cone',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 6,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone2.jpg'),
                itemName: 'Icecream Cone Red Cone',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 15,
            },
        ]
    },
    {
        id: 54,
        category: 'Icecream',
        name: "lush-Crush",
        branches: ['Branch1', 'Branch2'],
        picture: require('../assets/img/restaurantIcon/lush-Crush.png'),
        rating: 2.5,
        menuList: [
            {
                id: 0,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone3.jpg'),
                itemName: 'Icecream',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 13,
            },
            {
                id: 1,
                itemImg: require('../assets/img/menu/Icecream/IcecreamCone5.jpg'),
                itemName: 'Icecream Cone',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 15,
            },
            {
                id: 2,
                itemImg: require('../assets/img/menu/Icecream/IcecreamWaffle2.jpg'),
                itemName: 'Icecream Waffle',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'future',
                itemPrice: 18,
            },
            {
                id: 3,
                itemImg: require('../assets/img/menu/Icecream/IcecreamWaffle3.jpg'),
                itemName: 'Icecream Waffle 990',
                itemDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                itemType: 'normal',
                itemPrice: 20,
            },
        ]
    },
];


export default RestaurantList;